#!/bin/bash

set -e

export GOPATH=$PWD
go get github.com/jteeuwen/go-bindata
go install github.com/jteeuwen/go-bindata
bin/go-bindata -pkg db -func schema_sql -out src/h0tb0x/db/schema_sql.go src/h0tb0x/db/schema.sql 
go get h0tb0x
go fmt h0tb0x/...
go install h0tb0x
