PRAGMA user_version = 1;

DROP TABLE IF NOT EXISTS Object;
DROP TABLE IF NOT EXISTS Friend;
DROP TABLE IF NOT EXISTS TopicFriend;
DROP TABLE IF NOT EXISTS Blob;
DROP TABLE IF NOT EXISTS Advert;

CREATE UNIQUE INDEX IDX_Rendezvous_fp ON Rendezvous (fingerprint);
